---
abstract: 'HTTP Cookie jars for Furl.'
author:
  - 'root <root@localdomain>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Furl-Cookies
no_index:
  directory:
    - t
    - inc
requires:
  Time::Local: 1.2300
version: 0.03
